### ISSUE TITLE
twistedchecker thinks a '#' in a string starts a comment, complains

### ISSUE THREAD

**Issue by wsanchez** [twisted/twistedchecker#121]
I made this change: https://github.com/twisted/twisted/pull/620/commits/9c0d56c26a26cee6afda01efe6b876f39613036e

Because:
 * W9401: Comments should begin with one whitespace
 * W9402: The first letter of comment should be capitalized

See: https://travis-ci.org/twisted/twisted/jobs/181781383

**Comment by adiroiban** [comment]
This looks like a duplicate for #103 and  #110

**Comment by wsanchez** [comment]
#103 is about capitalization requirements in comments, and seems unrelated.

This is a dup of #110, though.
