### ISSUE TITLE
twistedchecker mandates @param on options

### ISSUE THREAD

**Issue by moshez** [twisted/twistedchecker#134]
Context: https://github.com/twisted/twisted/pull/601#issuecomment-262439865

**Comment by adiroiban** [comment]
Thanks for the report. If you have time, please fill a full bug report including the expected result and the actual result and tips for reproducing the bug.

The provided link makes a reference to an IRC discussion which is not references.

**Comment by moshez** [comment]
You can reproduce the bug by running twistedchecker on https://github.com/twisted/twisted/pull/601/commits/b30c227d8c3f3fc8f21bb56fd0cf523b672bcc35

The expected result is no complaint on the missing "@param" in twisted.web.tap.Options.opt_port.

The actual result is such a complaint.

The discussion on IRC can be summarized as "twistedchecker makes me have worse help messages."

The work around is described in https://github.com/twisted/twisted/pull/601#issuecomment-262439865

(by @glyph)
```
Options.opt_port.doc = Options.opt_port.doc.split("@Param")[0])
```
