### ISSUE TITLE
A shortcut to compare result with lastest result of buildbot

### ISSUE THREAD

**Issue by exarkun-insecure** [twisted/twistedchecker#35]
Add a shortcut for "--diff" option to allow user just type "twistedchecker --diff buildbot foo"

to compare the result of their codes with latest success result of buildbot.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2012-11-27T04:55:01Z
 * owner: zomux
 * the launchpad url was https://bugs.launchpad.net/bugs/1083431

**Comment by glyph** [comment]
I think that this is overly specific; I'm working on something that might be a better approach to the underlying problem in https://github.com/twisted/vertex/pull/38.
