### ISSUE TITLE
String formatting warning on things that aren't string formatting

### ISSUE THREAD

**Issue by exarkun-insecure** [twisted/twistedchecker#48]
Code such as "5 % 2" produces the warning: "String formatting operations should always use a tuplefor non-mapping values."

Obviously this isn't a string. (Also "tuplefor" seems to be a typo in the message.)

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-04-06T14:43:35Z
 * owner: jjacobs
 * the launchpad url was https://bugs.launchpad.net/bugs/1165416

**Comment by adiroiban** [comment]
I have checked to code on master and it pass. I think that this was fixed by @glyph at 3ab4dda

please reopen with an example if you think that this is still an error.

Thanks!
