### ISSUE TITLE
 in a docstring considered the beginning of a comment

### ISSUE THREAD

**Issue by exarkun-insecure** [twisted/twistedchecker#54]
Twistedchecker issued error 9401 - 'Comments should begin with one whitespace' when the following line appeared in a docstring

    Lines beginning with a C{#} are comments.

If the # appears with a space after it instead of the }, no error is generated.

# with docstrings should probably be ignored.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-08-27T00:38:15Z
 * owner: staceysern
 * the launchpad url was https://bugs.launchpad.net/bugs/1217144

**Comment by adiroiban** [comment]
Based on the work on #50 this should no longer be raised.

I am closing it as this should be fixed in #50
