### ISSUE TITLE
Complain if a branch / patch has no newsfile

### ISSUE THREAD

**Issue by adiroiban** [twisted/twistedchecker#90]
While old contributors already have the reflex of creating a newsfile for each branch/ticket I think that it would help new contributors if twistedchecker (or some other tools) would gently remind when branch is not quite ready to be merged, due to missing news file.

**Comment by tomprince** [comment]
Some other tool does this now (https://github.com/twisted/twisted/blob/trunk/bin/admin/check-topfile).
